#!/usr/bin/env bash
# Install and configure HAproxy on a load balancer server
# Configure HAproxy so that it send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

sudo apt-get -y update
sudo apt-get -y install haproxy
# sudo apt-get install --no-install-recommends software-properties-common
# sudo add-apt-repository ppa:vbernat/haproxy-2.6
# sudo apt-get install haproxy=2.6.\*

# Ensure HAproxy can be managed via an init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

echo -e "\n# HAproxy for web servers\nfrontend web-frontend\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 123992-web-01 35.168.3.38 check\n\tserver 123992-web-02 100.24.238.105 check" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
